/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrs.view.panel;

import br.edu.ifrs.controller.ListagemOficinaController;


/**
 *
 * @author Daniel M. Kuhn
 */
public class PanelListagemOficina extends javax.swing.JPanel {

    private ListagemOficinaController listagemoficinacontroller;
    
    /**
     * Creates new form home
     */
    public PanelListagemOficina() {
        initComponents();
        // popula a tabela
        listagemoficinacontroller.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ktable1 = new br.com.cyber.componente.Ktable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etBuscar = new br.com.cyber.componente.KTextField();
        btBuscar = new br.com.cyber.componente.KButton();
        btClear = new br.com.cyber.componente.KButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtOficina = new br.com.cyber.componente.Ktable();
        btAdicionarOficina = new br.com.cyber.componente.KButton();
        kLabel1 = new br.com.cyber.componente.KLabel();

        ktable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ktable1);

        setBackground(new java.awt.Color(254, 254, 254));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(740, 520));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("Busca");
        add(jLabel1);
        jLabel1.setBounds(80, 170, 120, 20);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setText("Controle de Oficinas");
        add(jLabel2);
        jLabel2.setBounds(79, 42, 450, 48);

        etBuscar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        etBuscar.setK_back_focus_gained(new java.awt.Color(204, 0, 51));
        etBuscar.setK_bord_focus_gained(new java.awt.Color(51, 51, 255));
        add(etBuscar);
        etBuscar.setBounds(79, 199, 370, 35);

        btBuscar.setBackground(new java.awt.Color(38, 193, 93));
        btBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar.setText("Buscar");
        btBuscar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btBuscar.setOriginal_bk_color(new java.awt.Color(0, 153, 153));
        add(btBuscar);
        btBuscar.setBounds(470, 200, 100, 34);

        btClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrs/imagens/eraser-16.png"))); // NOI18N
        add(btClear);
        btClear.setBounds(580, 200, 46, 34);

        jtOficina.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtOficina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Data Inicial", "Data Final", "Carga Horária", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtOficina.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtOficina.setGridColor(new java.awt.Color(0, 0, 0));
        jtOficina.setPreferredSize(new java.awt.Dimension(300, 88));
        jtOficina.setSelectionBackground(new java.awt.Color(38, 193, 93));
        jScrollPane3.setViewportView(jtOficina);

        add(jScrollPane3);
        jScrollPane3.setBounds(30, 270, 700, 250);

        btAdicionarOficina.setBackground(new java.awt.Color(38, 193, 93));
        btAdicionarOficina.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionarOficina.setText("Adicionar Oficina");
        btAdicionarOficina.setBk_focus_gained(new java.awt.Color(38, 193, 93));
        btAdicionarOficina.setBk_focus_lost(new java.awt.Color(38, 193, 93));
        btAdicionarOficina.setBorderPainted(false);
        btAdicionarOficina.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add(btAdicionarOficina);
        btAdicionarOficina.setBounds(79, 124, 186, 34);

        kLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrs/imagens/listas.jpg"))); // NOI18N
        add(kLabel1);
        kLabel1.setBounds(0, 0, 750, 540);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static br.com.cyber.componente.KButton btAdicionarOficina;
    public static br.com.cyber.componente.KButton btBuscar;
    public static br.com.cyber.componente.KButton btClear;
    public static br.com.cyber.componente.KTextField etBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static br.com.cyber.componente.Ktable jtOficina;
    private br.com.cyber.componente.KLabel kLabel1;
    private br.com.cyber.componente.Ktable ktable1;
    // End of variables declaration//GEN-END:variables
}
