/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrs.view.panel;


import br.edu.ifrs.controller.ListagemPessoaController;

/**
 *
 * @author Daniel M. Kuhn
 */
public class PanelTelaInicial extends javax.swing.JPanel {

    private ListagemPessoaController listagempessoacontroller;
    
    /**
     * Creates new form home
     */
    public PanelTelaInicial() {
        initComponents();
        // popula a tabela
        listagempessoacontroller.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ktable1 = new br.com.cyber.componente.Ktable();
        jLabel2 = new javax.swing.JLabel();
        btAdicionarPessoa = new br.com.cyber.componente.KButton();
        kLabel1 = new br.com.cyber.componente.KLabel();

        ktable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ktable1);

        setBackground(new java.awt.Color(254, 254, 254));
        setBorder(new javax.swing.border.SoftBevelBorder(0));
        setPreferredSize(new java.awt.Dimension(740, 520));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setText("Gerador de Certificados");
        add(jLabel2);
        jLabel2.setBounds(120, 70, 510, 48);

        btAdicionarPessoa.setBackground(new java.awt.Color(38, 193, 93));
        btAdicionarPessoa.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionarPessoa.setText("Adicionar Pessoas");
        btAdicionarPessoa.setAutoscrolls(true);
        btAdicionarPessoa.setBk_focus_gained(new java.awt.Color(38, 193, 93));
        btAdicionarPessoa.setBk_focus_lost(new java.awt.Color(38, 193, 93));
        btAdicionarPessoa.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add(btAdicionarPessoa);
        btAdicionarPessoa.setBounds(290, 240, 200, 34);

        kLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrs/imagens/listas.jpg"))); // NOI18N
        add(kLabel1);
        kLabel1.setBounds(0, 0, 750, 540);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static br.com.cyber.componente.KButton btAdicionarPessoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private br.com.cyber.componente.KLabel kLabel1;
    private br.com.cyber.componente.Ktable ktable1;
    // End of variables declaration//GEN-END:variables
}
