/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrs.view.panel;

/**
 *
 * @author Daniel M. Kuhn
 */
public class PanelAdicionarPessoa extends javax.swing.JPanel {

    /**
     * Creates new form adicionar
     */
    public PanelAdicionarPessoa() {
        initComponents();

        pnAlert.setVisible(false); // inicialmente o panel de alerta fica escondido

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtCPF = new javax.swing.JLabel();
        pnAlert = new javax.swing.JPanel();
        lbAlert = new javax.swing.JLabel();
        lbIconAlert = new javax.swing.JLabel();
        btCSV = new br.com.cyber.componente.KButton();
        etEmail = new br.com.cyber.componente.KTextField();
        btExcluir = new br.com.cyber.componente.KButton();
        btAdicionar = new br.com.cyber.componente.KButton();
        etNome = new br.com.cyber.componente.KTextField();
        etCPF = new br.com.cyber.componente.KTextField();
        Fundo = new br.com.cyber.componente.KLabel();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        txtTitulo.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Adicionar Pessoa");
        jPanel1.add(txtTitulo);
        txtTitulo.setBounds(0, 20, 600, 48);

        txtNome.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtNome.setText("Nome*");
        jPanel1.add(txtNome);
        txtNome.setBounds(70, 93, 80, 30);

        txtEmail.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtEmail.setText("E-mail*");
        jPanel1.add(txtEmail);
        txtEmail.setBounds(70, 172, 110, 33);

        txtCPF.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtCPF.setText("CPF*");
        jPanel1.add(txtCPF);
        txtCPF.setBounds(70, 251, 60, 33);

        pnAlert.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N

        lbAlert.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        lbAlert.setForeground(new java.awt.Color(254, 91, 91));
        lbAlert.setText("Null");

        javax.swing.GroupLayout pnAlertLayout = new javax.swing.GroupLayout(pnAlert);
        pnAlert.setLayout(pnAlertLayout);
        pnAlertLayout.setHorizontalGroup(
            pnAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlertLayout.createSequentialGroup()
                .addGroup(pnAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAlertLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lbIconAlert))
                    .addGroup(pnAlertLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAlertLayout.setVerticalGroup(
            pnAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAlertLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIconAlert)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAlertLayout.createSequentialGroup()
                .addComponent(lbAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnAlert);
        pnAlert.setBounds(200, 320, 250, 50);

        btCSV.setBackground(new java.awt.Color(38, 193, 93));
        btCSV.setForeground(new java.awt.Color(255, 255, 255));
        btCSV.setText("Adicionar por CSV");
        btCSV.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(btCSV);
        btCSV.setBounds(70, 390, 200, 34);

        etEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        etEmail.setK_back_error(new java.awt.Color(255, 153, 153));
        etEmail.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        etEmail.setK_bord_error(new java.awt.Color(255, 102, 102));
        etEmail.setK_bord_focus_gained(new java.awt.Color(38, 193, 93));
        etEmail.setK_obrigatory(true);
        jPanel1.add(etEmail);
        etEmail.setBounds(70, 200, 430, 35);

        btExcluir.setBackground(new java.awt.Color(38, 193, 93));
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Cancelar");
        btExcluir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(btExcluir);
        btExcluir.setBounds(468, 390, 120, 34);

        btAdicionar.setBackground(new java.awt.Color(38, 193, 93));
        btAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionar.setText("Adicionar");
        btAdicionar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btAdicionar);
        btAdicionar.setBounds(70, 330, 120, 34);

        etNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        etNome.setK_back_error(new java.awt.Color(255, 153, 153));
        etNome.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        etNome.setK_bord_error(new java.awt.Color(255, 102, 102));
        etNome.setK_bord_focus_gained(new java.awt.Color(38, 193, 93));
        etNome.setK_obrigatory(true);
        jPanel1.add(etNome);
        etNome.setBounds(70, 120, 430, 35);

        etCPF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        etCPF.setK_back_error(new java.awt.Color(255, 153, 153));
        etCPF.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        etCPF.setK_bord_error(new java.awt.Color(255, 102, 102));
        etCPF.setK_bord_focus_gained(new java.awt.Color(38, 193, 93));
        etCPF.setK_obrigatory(true);
        jPanel1.add(etCPF);
        etCPF.setBounds(70, 280, 430, 35);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrs/imagens/addpessoa.jpg"))); // NOI18N
        jPanel1.add(Fundo);
        Fundo.setBounds(-7, -4, 610, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.cyber.componente.KLabel Fundo;
    public static br.com.cyber.componente.KButton btAdicionar;
    public static br.com.cyber.componente.KButton btCSV;
    public static br.com.cyber.componente.KButton btExcluir;
    public static br.com.cyber.componente.KTextField etCPF;
    public static br.com.cyber.componente.KTextField etEmail;
    public static br.com.cyber.componente.KTextField etNome;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbAlert;
    public static javax.swing.JLabel lbIconAlert;
    public static javax.swing.JPanel pnAlert;
    private javax.swing.JLabel txtCPF;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
