/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrs.view.panel;


/**
 *
 * @author Daniel M. Kuhn
 */
public class PanelAlterarPessoa extends javax.swing.JPanel {

    
    /**
     * Creates new form AlterarPessoa
     */
    public PanelAlterarPessoa() {
        initComponents();
        
        pnAlert.setVisible(false); // inicialmente o panel de alerta fica escondido

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        pnAlert = new javax.swing.JPanel();
        lbAlert = new javax.swing.JLabel();
        lbIconAlert = new javax.swing.JLabel();
        etNome = new br.com.cyber.componente.KTextField();
        etEmail = new br.com.cyber.componente.KTextField();
        btAlterar = new br.com.cyber.componente.KButton();
        Fundo = new br.com.cyber.componente.KLabel();

        setPreferredSize(new java.awt.Dimension(600, 450));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(null);

        txtTitulo.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Alterar Pessoa");
        jPanel1.add(txtTitulo);
        txtTitulo.setBounds(0, 20, 550, 48);

        txtNome.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtNome.setText("Nome");
        jPanel1.add(txtNome);
        txtNome.setBounds(70, 93, 60, 33);

        txtEmail.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtEmail.setText("E-mail");
        jPanel1.add(txtEmail);
        txtEmail.setBounds(70, 173, 90, 33);

        lbAlert.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lbAlert.setForeground(new java.awt.Color(254, 91, 91));
        lbAlert.setText("Null");

        javax.swing.GroupLayout pnAlertLayout = new javax.swing.GroupLayout(pnAlert);
        pnAlert.setLayout(pnAlertLayout);
        pnAlertLayout.setHorizontalGroup(
            pnAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIconAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnAlertLayout.setVerticalGroup(
            pnAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAlertLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIconAlert)
                .addGap(33, 33, 33))
            .addGroup(pnAlertLayout.createSequentialGroup()
                .addComponent(lbAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnAlert);
        pnAlert.setBounds(185, 332, 284, 46);

        etNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        etNome.setK_back_error(new java.awt.Color(253, 153, 153));
        etNome.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        etNome.setK_bord_error(new java.awt.Color(238, 102, 102));
        etNome.setK_obrigatory(true);
        jPanel1.add(etNome);
        etNome.setBounds(70, 120, 399, 35);

        etEmail.setBackground(new java.awt.Color(255, 153, 153));
        etEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        etEmail.setK_back_error(new java.awt.Color(255, 153, 153));
        etEmail.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        etEmail.setK_bord_error(new java.awt.Color(255, 102, 102));
        etEmail.setK_obrigatory(true);
        jPanel1.add(etEmail);
        etEmail.setBounds(70, 200, 399, 35);

        btAlterar.setBackground(new java.awt.Color(38, 193, 93));
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setText("Alterar");
        btAlterar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(btAlterar);
        btAlterar.setBounds(70, 332, 103, 46);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifrs/imagens/addpessoa.jpg"))); // NOI18N
        jPanel1.add(Fundo);
        Fundo.setBounds(0, 0, 610, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.cyber.componente.KLabel Fundo;
    public static br.com.cyber.componente.KButton btAlterar;
    public static br.com.cyber.componente.KTextField etEmail;
    public static br.com.cyber.componente.KTextField etNome;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbAlert;
    public static javax.swing.JLabel lbIconAlert;
    public static javax.swing.JPanel pnAlert;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
