/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrs.view.exec;


import br.edu.ifrs.controller.ListagemOficinaController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Daniel M. Kuhn
 */
public class ListagemOficina extends javax.swing.JFrame {


        private static ListagemOficina listagemoficina;
    
    /**
     * Creates new form ListagemProduto
     */
    public ListagemOficina() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        
        
        // listeners do botao Adicionar Produto ao pressionar enter e clicar
        
        panellistagemoficina.btAdicionarOficina.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mousePressed(MouseEvent e) {
                AdicionarOficina ap = new AdicionarOficina(listagemoficina, true);
                ap.setVisible(true);
            }
        });
        
        panellistagemoficina.btAdicionarOficina.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyPressed(KeyEvent e) {
                
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    AdicionarOficina ap = new AdicionarOficina(listagemoficina, true);
                    ap.setVisible(true);
                }
            }
        });
        
        
        // listeners do botao Search ao pressionar enter e clicar
        
        panellistagemoficina.btBuscar.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    ListagemOficinaController lpc = new ListagemOficinaController();
                    lpc.atualizaTabela();
                }
            }
        });
        
        
        panellistagemoficina.btBuscar.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mousePressed(MouseEvent e) {
                ListagemOficinaController lpc = new ListagemOficinaController();
                lpc.atualizaTabela();
            }
        });
        
        
        // listeners do Campo Search ao pressionar enter
        
        panellistagemoficina.etBuscar.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    ListagemOficinaController lpc = new ListagemOficinaController();
                    lpc.atualizaTabela();
                }
            }
        });
        
        
        // listeners do botao Limpar Busca ao pressionar enter e clicar
        
        panellistagemoficina.btClear.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    ListagemOficinaController lpc = new ListagemOficinaController();
                    lpc.limpaCampoBusca();
                    lpc.atualizaTabela();
                }
            }
        });
        
        
        panellistagemoficina.btClear.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseClicked(MouseEvent e) {
                ListagemOficinaController lpc = new ListagemOficinaController();
                lpc.limpaCampoBusca();
                lpc.atualizaTabela();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellistagemoficina = new br.edu.ifrs.view.panel.PanelListagemOficina();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellistagemoficina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellistagemoficina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemOficina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.edu.ifrs.view.panel.PanelListagemOficina panellistagemoficina;
    // End of variables declaration//GEN-END:variables
}
